### ISSUE TITLE
Add `$schema` as property

### ISSUE THREAD

**Issue by tschmidtb51** [OpenPLF/oplf#3]
To match and check the schema automatically, we should add a `$schema` as property and make it mandatory.

**Comment by santosomar** [comment]
You're right; adding a `$schema` property is important for specifying which version of JSON Schema the document is written in, and it should be mandatory. In the example I provided earlier, the `$schema` property is already included at the beginning of the schema.

**Comment by santosomar** [comment]
I added you as a collaborator @tschmidtb51 . I may create a GitHub org shortly. Perhaps start with the Open Product Lifecycle Framework (OPLF) name??

**Comment by santosomar** [comment]
@tschmidtb51  can you review #5 ?
