### ISSUE TITLE
Consider adding a creation timestamp

### ISSUE THREAD

**Issue by tschmidtb51** [OpenPLF/oplf#4]
This is especially helpful, when you have multiple such statements with different content (to figure out which one is the latest).

**Comment by santosomar** [comment]
Adding a creation timestamp is a great idea as it provides information on when the EOL and EOS record was created. I will update the schema with the "creationTimestamp" property included...

**Comment by santosomar** [comment]
This was addressed in https://github.com/OpenPLF/oplf/pull/8
